Update github-actions-demo.yml

diff --git a/.github/workflows/github-actions-demo.yml b/.github/workflows/github-actions-demo.yml
--- a/.github/workflows/github-actions-demo.yml
+++ b/.github/workflows/github-actions-demo.yml
@@ -1,24 +1,21 @@
-name:  01 - Building Blocks.
+name: 01 - Building Blocks
 
 on: push
 
-   
 jobs:
   echo-hello:
     runs-on: ubuntu-latest
     steps:
-        - name: Say Hello
-          run: echo "Hello, World!"
+      - name: Say Hello
+        run: echo "Hello, World!"
 
   echo-goodbye:
     runs-on: ubuntu-latest
     steps:
       - name: Failed step
         run: |
-            echo "I will fail"
-            exit 1
-      
-     -  name: Say goodbye
+          echo "I will fail"
+          exit 1
+
+      - name: Say goodbye
         run: echo "Goodbye!"
-  
-  
